//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Call :ExtensionCall, IEntityWithID
    {
        public System.Guid ID { get; set; }
        public string UnitName { get; set; }
        public string Kc { get; set; }
        public string Codec { get; set; }
        public string Rate { get; set; }
        public string TS { get; set; }
        public string CallerNumber { get; set; }
        public string FileName { get; set; }
        public string CipherMode { get; set; }
        public string TMSI { get; set; }
        public string IMSI { get; set; }
        public string IMEI { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> ARFCNID { get; set; }
        public string Size { get; set; }
    
        public virtual ARFCN ARFCN { get; set; }
    }
}
