//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPI.Models.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class Computer : IEntityWithID
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string IP { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string System { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> Receivers { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.Guid> Unit_ID { get; set; }
    
        public virtual Unit Unit { get; set; }
    }
}
