//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPI.Models.Entity
{
    using CPI.Models.Helpers;
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver : ExtensionReceiver, IEntityWithID
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ARFCN_ID { get; set; }
        public Nullable<System.Guid> Comp_ID { get; set; }
    
        public virtual ARFCN ARFCN { get; set; }
        public virtual Computer Computer { get; set; }
    }
}
