//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPI.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting : IEntityWithID
    {
        public System.Guid ID { get; set; }
        public string Key { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
        public string DefaultValue { get; set; }
    }
}
